parameters:
#    anthony_crud.example.class: Anthony\Bundle\CrudBundle\Example

services:
#    anthony_crud.example:
#        class: %anthony_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
